# Generated by Django 5.1.4 on 2025-01-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="duration",
        ),
        migrations.AddField(
            model_name="service",
            name="duration_minutes",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(default="service", max_length=50),
            preserve_default=False,
        ),
    ]
