# Generated by Django 5.1.4 on 2025-01-03 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0002_remove_service_duration_service_duration_minutes_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="duration_minutes",
            new_name="duration",
        ),
    ]
