# Generated by Django 5.1.4 on 2025-01-04 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trainer", "0003_rename_duration_minutes_service_duration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trainerdescription",
            name="trainer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="description",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
