# Generated by Django 5.1.4 on 2025-01-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
        ("trainer", "0005_alter_trainerschedule_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="trainer.service",
            ),
        ),
    ]
